#!/bin/bash

set -e

. /usr/share/debconf/confmodule

function set_up_csf() {
  local reload_csf="false"
  local p k

  if [ ! -e /etc/csf/csf.conf ]; then
    >&2 echo "I: csf not installed. Not opening ports for gasstation-express-oracle."
    return
  fi

  # Ports
  if [ ! "$host" == "localhost" ]; then
    n=$(csf-config open-ports TCP_OUT "$port")
    if [[ $n -gt 0 ]]; then
      reload_csf="true"
    fi
  fi

  # Process ignores
  local pignores="$pignores""cmd:/usr/bin/python3 /srv/local/eth-gasexpress/gasExpress.py"$'\x1e'
  if ! n=$(csf-ignore "$pignores"); then
    >&2 echo "E: Couldn't add gasstation-express-oracle ignores to csf pignore file"
  elif [ "$(echo "$n" | wc -l)" -gt 0 ]; then
    reload_csf="true"
  fi

  if [ "$reload_csf" == "true" ]; then
    dpkg-trigger --no-await csf-reload
  fi
}

db_get eth-gasexpress/svc-user
SVCUSER="$RET"

db_get eth-gasexpress/rpc-host
host="$RET"

db_get eth-gasexpress/rpc-port
port="$RET"

ACTION="$1"
if [ "$DEBCONF_RECONFIGURE" == '1' ]; then
    ACTION="reconfigure"
fi

# Run every install
if [ "$ACTION" != 'triggered' ]; then
    # Create service user/group
    if ! grep -q "^$SVCUSER:" /etc/passwd; then
        if ! grep -q "^$SVCUSER:" /etc/group; then
            groupadd "$SVCUSER"
        fi
        useradd -g "$SVCUSER" -M -r "$SVCUSER"
    fi

    # Own the service directory
    chown -R "$SVCUSER:$SVCUSER" /srv/local/eth-gasexpress

    # Setguid for all directories in service directory
    find /srv/local/eth-gasexpress -type d -exec chmod g+s "{}" \;

    # Make sure python dependencies are up to date
    pip3 install -t /srv/local/eth-gasexpress/vendor -r /srv/local/eth-gasexpress/requirements.txt || true

    # Populate the service template and place
    cat /usr/share/eth-gasexpress/eth-gasexpress.service.template | 
      sed "s/%host%/$host/" |
      sed "s/%port%/$port/" | 
      sed "s/%user%/$SVCUSER/" \
      > /lib/systemd/system/eth-gasexpress.service

    set_up_csf

    # Enable the service on fresh installs
    if dpkg --compare-versions "$2" lt "1.0.0"; then
        systemctl enable --now eth-gasexpress.service
    fi
fi





# Triggers
if [ "$ACTION" == "triggered" ]; then
  if [ "$2" == "csf-hardening-changed" ]; then
    set_up_csf
  fi
fi
